### ISSUE TITLE
When I type the !rank command this error pops up "Cannot assign role newbie as Mee6 Helper does not have the necessary permissions." Please help me.

### ISSUE THREAD

**Issue by AskewCow** [JDiscordBots/Mee6-bypasser#14]
**Describe the question**
A clear and concise description of what you want to know.

**Is your Question related to a problem? Please describe.**

**Additional context**
Add any other context or screenshots about the question here.

**Comment by danthe1st** [comment]
You need to give `Mee6-bypasser` the permission `MANAGE_ROLES`. This role of `Mee6-bypasser` must also be higher than all roles that it should assign.
