### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Hachi899** [JDiscordBots/Mee6-bypasser#19]
Hi,

Doing !rank doesn't update the roles. I followed the instructions on the previous bug reports but it still doesn't work. The server I am in has approximately 250 and around 20 active members. Do you know what the issue is? If so, is this something that can be fixed?

Thanks.

**Comment by Hachi899** [comment]
Nevermind, it's working now.

**Comment by danthe1st** [comment]
Also a duplicate of #17
